2025-07-08T20:31:00.889874891Z       Program python found: YES (/opt/render/project/src/.venv/bin/python)
2025-07-08T20:31:00.889876951Z       Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
2025-07-08T20:31:00.889879011Z       Run-time dependency python found: YES 3.13
2025-07-08T20:31:00.889901043Z       Program cython found: YES (/tmp/pip-build-env-rdm1iex8/overlay/bin/cython)
2025-07-08T20:31:00.889905584Z       Compiler for C supports arguments -Wno-unused-but-set-variable: YES
2025-07-08T20:31:00.889907764Z       Compiler for C supports arguments -Wno-unused-function: YES
2025-07-08T20:31:00.889909804Z       Compiler for C supports arguments -Wno-conversion: YES
2025-07-08T20:31:00.889911884Z       Compiler for C supports arguments -Wno-misleading-indentation: YES
2025-07-08T20:31:00.889914014Z       Library m found: YES
2025-07-08T20:31:00.889916114Z       
2025-07-08T20:31:00.889919025Z       ../meson.build:78:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang-new'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
2025-07-08T20:31:00.889921185Z       The following exception(s) were encountered:
2025-07-08T20:31:00.889923375Z       Running `gfortran --help` gave "[Errno 2] No such file or directory: 'gfortran'"
2025-07-08T20:31:00.889925515Z       Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
2025-07-08T20:31:00.889927565Z       Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
2025-07-08T20:31:00.889929655Z       Running `flang-new --help` gave "[Errno 2] No such file or directory: 'flang-new'"
2025-07-08T20:31:00.889931806Z       Running `flang-new --version` gave "[Errno 2] No such file or directory: 'flang-new'"
2025-07-08T20:31:00.889934256Z       Running `flang-new -V` gave "[Errno 2] No such file or directory: 'flang-new'"
2025-07-08T20:31:00.889936336Z       Running `flang --help` gave "[Errno 2] No such file or directory: 'flang'"
2025-07-08T20:31:00.889938396Z       Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
2025-07-08T20:31:00.889940806Z       Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
2025-07-08T20:31:00.889942927Z       Running `nvfortran --help` gave "[Errno 2] No such file or directory: 'nvfortran'"
2025-07-08T20:31:00.889945016Z       Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
2025-07-08T20:31:00.889947077Z       Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
2025-07-08T20:31:00.889949197Z       Running `pgfortran --help` gave "[Errno 2] No such file or directory: 'pgfortran'"
2025-07-08T20:31:00.889951217Z       Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
2025-07-08T20:31:00.889953287Z       Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
2025-07-08T20:31:00.889955337Z       Running `ifort --help` gave "[Errno 2] No such file or directory: 'ifort'"
2025-07-08T20:31:00.889961998Z       Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
2025-07-08T20:31:00.889964128Z       Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
2025-07-08T20:31:00.889966178Z       Running `ifx --help` gave "[Errno 2] No such file or directory: 'ifx'"
2025-07-08T20:31:00.889968178Z       Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
2025-07-08T20:31:00.889970209Z       Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
2025-07-08T20:31:00.889972419Z       Running `g95 --help` gave "[Errno 2] No such file or directory: 'g95'"
2025-07-08T20:31:00.889974579Z       Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
2025-07-08T20:31:00.889977159Z       Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
2025-07-08T20:31:00.889979259Z       
2025-07-08T20:31:00.889997051Z       A full log can be found at /tmp/pip-install-ocrwlia5/scipy_5b2275a77bef44b6910e259f6319a3ec/.mesonpy-g0ldkm4x/meson-logs/meson-log.txt
2025-07-08T20:31:00.890000971Z       [end of output]
2025-07-08T20:31:00.890004261Z   
2025-07-08T20:31:00.890007631Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2025-07-08T20:31:00.896671035Z error: metadata-generation-failed
2025-07-08T20:31:00.896682425Z 
2025-07-08T20:31:00.896685456Z Ã— Encountered error while generating package metadata.
2025-07-08T20:31:00.896687926Z â•°â”€> See above for output.
2025-07-08T20:31:00.896689846Z 
2025-07-08T20:31:00.896692346Z note: This is an issue with the package mentioned above, not pip.
2025-07-08T20:31:00.896694486Z hint: See above for details.
2025-07-08T20:31:01.497334532Z ==> Build failed ðŸ˜ž
2025-07-08T20:31:01.497355963Z ==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys